version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/ws"
    schedule:
      interval: "weekly"
