
### ✅ Pull Request Template 

---

**Title:**

<!-- Concise, descriptive title (e.g. "Add feature to parse TOML config files") -->

---

#### 🔍 Description

<!-- Describe the changes in this PR. What does it fix/add/remove/change? -->

* Closes: #\[issue\_number] (if applicable)
* Type: `feature` / `bugfix` / `refactor` / `chore` / `docs`

---

#### 🧪 Testing

<!-- Explain how you tested this. Include steps or commands if needed. -->

* [ ] `cargo test` passes
* [ ] Manually tested new functionality
* [ ] Added/updated unit or integration tests

---

#### 📚 Documentation

<!-- Have you updated relevant documentation (README, module docs, comments)? -->

* [ ] Rustdoc comments updated
* [ ] README updated
* [ ] No documentation needed

---

#### 🔍 Code Quality

<!-- Optional checklist for Rust-specific quality checks -->

* [ ] Code formatted (`cargo fmt`)
* [ ] Lint check passed (`cargo clippy`)
* [ ] No warnings introduced

---

#### ⚠️ Breaking Changes

<!-- List any breaking changes, or write "None" -->

* None

---

#### 📝 Notes for Reviewers

<!-- Any caveats, open questions, or things reviewers should pay extra attention to -->

---

You can save this as `.github/pull_request_template.md` in your repository to automatically populate new PRs with this template.

Would you like a simplified version or something more tailored to your workflow (e.g. async code, web backend, CLI tool, etc.)?
