name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Cache dependencies
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      # Install Rust
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build WebSocket
        working-directory: ./ws
        run: cargo build --verbose
      
      - name: Build API
        working-directory: ./api
        run: cargo build --verbose
